---
version: '2.4'
services:
  api:
    image: ghcr.io/ietf-tools/ietf-at:latest
    container_name: api
    environment:
      SENTRY_DSN: ${SENTRY_DSN}
      SITE_URL: ${SITE_URL}
    env_file:
      - ./at.env
    logging:
      driver: "syslog"
      options:
        syslog-address: "tcp://ietfa.amsl.com:514"
    restart: unless-stopped
    mem_limit: 4gb
  ui:
    image: ghcr.io/ietf-tools/ietf-at-ui:latest
    container_name: ui
    logging:
      driver: "syslog"
      options:
        syslog-address: "tcp://ietfa.amsl.com:514"
    restart: unless-stopped
    mem_limit: 500mb
  proxy:
    image: nginx:latest
    restart: unless-stopped
    env_file:
      - ./at.env
    depends_on:
      - api
      - ui
    links:
      - api
      - ui
    ports:
      - ${AT_PORT}:80
    volumes:
      - ./nginx-templates:/etc/nginx/templates/
    mem_limit: 500mb
